INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('0SZORK64', 'Jeans', 'Jeans3', NULL, NULL);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('8JP3HTNC', 'Shoes', 'Shoes2', 5.0, 260.65);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('AY12YIVF', 'Perfumes', 'Perfume5', 9.0, 240.93);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('02UPVSF5', 'Smart Phone', 'Phone5', 5.0, 231.0);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('UERJQENB', 'Water bottles', 'Bottle5', 6.0, 261.6);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('ZGEHUIQS', 'Tshirts', 'Tshirt6', 9.0, 352.08);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('9XRO37U9', 'Jeans', 'Jeans5', 3.0, 81.09);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('7GE3AI6A', 'Perfumes', 'Perfume5', 10.0, 470.3);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('E6SWYU2R', 'Water bottles', 'Bottle5', 7.0, 273.21);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('3GNDC06K', 'Smart Phone', 'Phone1', NULL, NULL);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('SBRP14XH', 'Shoes', 'Shoes6', 2.0, 96.96);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('32BH1A4O', 'Shoes', 'Shoes4', 10.0, 361.8);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('8VPCAYP9', 'Jeans', 'Jeans1', 5.0, 183.95);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('AX6KDD49', 'Water bottles', 'Bottle4', 2.0, 50.54);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('TDW7V1QS', 'Jeans', 'Jeans3', NULL, NULL);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('PHTN0UON', 'Tshirts', 'Tshirt3', 4.0, 165.28);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('USWETYX2', 'Smart Phone', 'Phone1', 9.0, 373.05);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('PN4U6AVE', 'Tshirts', 'Tshirt3', NULL, NULL);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('4WU3GA9T', 'Tshirts', 'Tshirt2', 6.0, 254.52);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('2NS8ERKD', 'Tshirts', 'Tshirt5', 3.0, 75.69);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('GCT2XFDZ', 'Water bottles', 'Bottle2', 7.0, 343.35);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('F7MVQ356', 'Smart Phone', 'Phone2', 3.0, 87.81);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('DTYN4BPS', 'Shoes', 'Shoes6', 5.0, 139.55);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('3ZA0CO76', 'Tshirts', 'Tshirt5', 6.0, 265.86);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('HE4QGFUL', 'Smart Phone', 'Phone3', 8.0, 237.36);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('RX6SFJQD', 'Water bottles', 'Bottle3', NULL, NULL);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('AC27X1CE', 'Smart Phone', 'Phone1', 9.0, 348.93);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('9XLP0BN8', 'Shoes', 'Shoes1', 8.0, 214.88);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('BQ3VYAR6', 'Smart Phone', 'Phone1', 3.0, 92.85);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('ULK3FUQV', 'Water bottles', 'Bottle1', 10.0, 360.0);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('EJ81O082', 'Perfumes', 'Perfume2', 7.0, 262.15);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('3C60CJBM', 'Perfumes', 'Perfume2', 4.0, 143.84);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('C6H52MJ1', 'Perfumes', 'Perfume6', 4.0, 120.8);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('TOJTBPGT', 'Jeans', 'Jeans3', 3.0, 122.64);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('HKG2N968', 'Water bottles', 'Bottle3', 9.0, 401.58);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('LB37ZOQM', 'Shoes', 'Shoes4', 9.0, 216.81);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('U0AB76LB', 'Tshirts', 'Tshirt3', 3.0, 93.63);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('9DI89QSN', 'Water bottles', 'Bottle6', 1.0, 51.96);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('2ZQOYGWO', 'Perfumes', 'Perfume6', NULL, NULL);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('ZCGACEPL', 'Perfumes', 'Perfume3', 6.0, 204.12);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('FP37CDHZ', 'Perfumes', 'Perfume3', 1.0, 22.42);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('P6MPB4DP', 'Jeans', 'Jeans3', 10.0, 336.3);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('7ZVNBI1C', 'Jeans', 'Jeans2', 9.0, 217.62);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('81AYUAM7', 'Tshirts', 'Tshirt4', 10.0, 316.9);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('Z1CTW689', 'Jeans', 'Jeans4', NULL, NULL);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('M1INUFNC', 'Shoes', 'Shoes5', 3.0, 139.53);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('AAU76TCN', 'Tshirts', 'Tshirt4', 10.0, 479.6);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('SYE6HG4L', 'Smart Phone', 'Phone4', 4.0, 174.08);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('OQ14MAFM', 'Water bottles', 'Bottle3', 1.0, 22.07);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('J6GDTGCG', 'Tshirts', 'Tshirt1', 7.0, 252.28);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('L4C0BB6P', 'Perfumes', 'Perfume6', 4.0, 127.64);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('1T6SIF6D', 'Water bottles', 'Bottle1', 1.0, 50.64);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('7KY87Q19', 'Smart Phone', 'Phone4', 3.0, 149.13);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('DVVPGB8I', 'Perfumes', 'Perfume5', 10.0, 303.3);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('NSCQQAVA', 'Water bottles', 'Bottle2', 3.0, 127.65);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('I1AGZGXV', 'Smart Phone', 'Phone1', 6.0, 175.38);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('S60YUP1S', 'Water bottles', 'Bottle2', 9.0, 248.04);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('CVL0YQZD', 'Jeans', 'Jeans5', 9.0, 420.57);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('117R1Z4C', 'Perfumes', 'Perfume5', NULL, NULL);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('RGSL55X9', 'Smart Phone', 'Phone5', 9.0, 433.17);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('AGHKE79E', 'Jeans', 'Jeans2', 8.0, 234.16);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('RKHE0SDP', 'Jeans', 'Jeans1', 5.0, 172.55);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('Y00EW9JZ', 'Shoes', 'Shoes5', 4.0, 89.68);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('R4E5IZB1', 'Jeans', 'Jeans2', 3.0, 125.13);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('OOA9CZV7', 'Jeans', 'Jeans5', 6.0, 144.54);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('DTECAFVO', 'Smart Phone', 'Phone4', 7.0, 337.82);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('5B8U8H7B', 'Water bottles', 'Bottle6', 5.0, 194.95);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('WOFC57PA', 'Jeans', 'Jeans6', 5.0, 124.85);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('46Q16NZ7', 'Tshirts', 'Tshirt3', 6.0, 244.5);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('NKK1JXPP', 'Tshirts', 'Tshirt5', 7.0, 267.68);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('UMKVGG4N', 'Jeans', 'Jeans6', 4.0, 128.36);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('HOE3MXZJ', 'Smart Phone', 'Phone1', 3.0, 100.35);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('5B08VYDW', 'Jeans', 'Jeans1', 9.0, 455.31);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('XUNHU25Z', 'Smart Phone', 'Phone2', 5.0, 128.8);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('YNII88BY', 'Shoes', 'Shoes4', 3.0, 115.26);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('TONZNQ06', 'Tshirts', 'Tshirt1', 6.0, 312.24);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('OZZ9Z76M', 'Perfumes', 'Perfume6', 6.0, 254.22);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('U9JN01N3', 'Jeans', 'Jeans3', 7.0, 270.48);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('GKAZAL4W', 'Smart Phone', 'Phone2', 3.0, 76.47);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('1VL7UO4G', 'Shoes', 'Shoes5', 6.0, 181.74);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('I1VEGE3B', 'Jeans', 'Jeans1', 5.0, 140.45);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('I673KLLZ', 'Water bottles', 'Bottle3', 10.0, 307.7);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('1I8YATYE', 'Tshirts', 'Tshirt4', 4.0, 206.24);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('C0Q6ULH3', 'Perfumes', 'Perfume3', 3.0, 82.14);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('6SQJY6RE', 'Water bottles', 'Bottle3', 3.0, 124.35);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('OM0F6QEP', 'Jeans', 'Jeans6', 1.0, 45.76);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('AKC37WMF', 'Water bottles', 'Bottle3', 4.0, 172.12);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('XXBAF4GE', 'Smart Phone', 'Phone5', 6.0, 219.72);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('PVIU21HO', 'Shoes', 'Shoes2', 4.0, 109.36);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('HHWMF1GZ', 'Water bottles', 'Bottle6', 3.0, 70.56);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('MZ8M6XHI', 'Perfumes', 'Perfume6', 8.0, 264.4);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('ZGSVANRY', 'Jeans', 'Jeans2', 8.0, 257.44);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('PS8QDB9B', 'Jeans', 'Jeans3', 4.0, 164.04);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('33HBAEOM', 'Jeans', 'Jeans4', 2.0, 89.4);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('U8Z8R2W7', 'Perfumes', 'Perfume2', 9.0, 472.32);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('HPJF9899', 'Shoes', 'Shoes5', 7.0, 304.29);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('W1K9M94U', 'Jeans', 'Jeans2', 9.0, 204.57);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('0MCG59MN', 'Water bottles', 'Bottle6', 3.0, 89.94);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('CXTJYRDI', 'Tshirts', 'Tshirt4', 8.0, 263.76);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('1XLAXHNO', 'Smart Phone', 'Phone6', 9.0, 321.21);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('UZXNLJRN', 'Tshirts', 'Tshirt5', 7.0, 225.82);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('XNPZCU7M', 'Shoes', 'Shoes5', 3.0, 150.45);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('DZVHLTMG', 'Smart Phone', 'Phone3', NULL, NULL);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('G9XC5REX', 'Smart Phone', 'Phone1', 1.0, 33.36);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('IZ6WQUQB', 'Jeans', 'Jeans3', 4.0, 190.76);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('RRCV1EXY', 'Perfumes', 'Perfume4', 3.0, 123.42);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('TRTM477Y', 'Tshirts', 'Tshirt4', 10.0, 458.5);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('D1LG8Y2W', 'Water bottles', 'Bottle6', 2.0, 98.2);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('EC41RN9U', 'Jeans', 'Jeans2', 1.0, 29.1);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('F8QLT1RK', 'Smart Phone', 'Phone3', 1.0, 22.02);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('PH6P9JLA', 'Smart Phone', 'Phone5', 5.0, 129.9);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('HVNJPGQC', 'Jeans', 'Jeans3', 4.0, 172.48);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('ZIHZVZGM', 'Water bottles', 'Bottle5', 3.0, 142.68);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('HK94W6WU', 'Jeans', 'Jeans5', 7.0, 366.17);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('OPKLJ670', 'Perfumes', 'Perfume3', 6.0, 207.84);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('WO7V1IZ4', 'Shoes', 'Shoes6', 2.0, 71.38);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('55JSYXUF', 'Shoes', 'Shoes5', 4.0, 191.28);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('VR79YT1S', 'Tshirts', 'Tshirt5', 7.0, 194.18);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('91QCG41R', 'Shoes', 'Shoes1', 2.0, 44.66);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('ZOM2E1BA', 'Shoes', 'Shoes5', 5.0, 251.65);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('7FVU3F0M', 'Shoes', 'Shoes3', 5.0, 195.6);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('45TVGUW4', 'Jeans', 'Jeans1', 8.0, 295.76);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('V7JMKJLN', 'Tshirts', 'Tshirt5', 2.0, 95.56);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('N5KG3FYE', 'Tshirts', 'Tshirt1', 9.0, 420.57);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('JHDKXZO0', 'Jeans', 'Jeans2', 5.0, 151.0);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('B29XZ6UK', 'Water bottles', 'Bottle6', 9.0, 208.89);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('XR6CJ9K4', 'Perfumes', 'Perfume1', 2.0, 102.16);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('F3VKOG10', 'Tshirts', 'Tshirt2', 6.0, 144.54);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('WIEEO9H5', 'Jeans', 'Jeans2', 9.0, 259.56);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('QCYYPQ7A', 'Jeans', 'Jeans1', 5.0, 201.75);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('M3I0GXHC', 'Smart Phone', 'Phone2', 10.0, 494.1);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('3GBJ72BT', 'Jeans', 'Jeans2', 9.0, 302.22);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('DZ8XEBNP', 'Smart Phone', 'Phone1', 10.0, 226.8);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('5Q1D7XYL', 'Water bottles', 'Bottle4', 5.0, 258.45);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('7BMTT7FY', 'Shoes', 'Shoes4', 10.0, 302.0);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('FV2VYN1K', 'Water bottles', 'Bottle2', 2.0, 60.14);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('RWQ1CGED', 'Shoes', 'Shoes5', 3.0, 99.3);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('IMYO7WY6', 'Tshirts', 'Tshirt1', 9.0, 214.38);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('Y27VMVWJ', 'Tshirts', 'Tshirt4', 8.0, 280.64);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('DG680IUG', 'Shoes', 'Shoes2', 2.0, 88.36);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('EGYYJ5N8', 'Tshirts', 'Tshirt3', 3.0, 85.32);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('HKK54K4R', 'Jeans', 'Jeans6', 9.0, 276.93);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('Q2ANY1YC', 'Perfumes', 'Perfume5', 1.0, 34.15);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('JZGPXF50', 'Shoes', 'Shoes2', 8.0, 354.48);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('R2FMFP5M', 'Smart Phone', 'Phone2', 8.0, 354.8);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('XU7FKC78', 'Tshirts', 'Tshirt2', 3.0, 69.63);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('L1ZOPQZF', 'Smart Phone', 'Phone2', NULL, NULL);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('1GPCXWAY', 'Smart Phone', 'Phone2', 5.0, 259.35);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('X1BJT4ZF', 'Shoes', 'Shoes1', 2.0, 64.0);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('8GC0S6EN', 'Water bottles', 'Bottle1', 3.0, 78.6);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('9KA1DLUC', 'Jeans', 'Jeans4', 9.0, 399.96);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('2G76RWR3', 'Shoes', 'Shoes3', 1.0, 23.87);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('O8OL0V0H', 'Perfumes', 'Perfume3', 7.0, 354.76);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('3GGAYBFJ', 'Water bottles', 'Bottle2', 3.0, 124.74);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('7U55D5Q3', 'Jeans', 'Jeans1', 8.0, 359.76);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('USXSH0AH', 'Smart Phone', 'Phone5', 10.0, 344.6);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('CMHFMTGD', 'Smart Phone', 'Phone4', 3.0, 66.21);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('J56TAMY7', 'Shoes', 'Shoes6', NULL, NULL);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('CQTP3174', 'Perfumes', 'Perfume2', 10.0, 494.9);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('VN28HR6C', 'Jeans', 'Jeans5', 4.0, 178.12);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('GQIT8D9G', 'Shoes', 'Shoes6', 9.0, 360.81);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('ZFY40I6Q', 'Water bottles', 'Bottle5', 4.0, 128.52);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('L70ZO6RD', 'Perfumes', 'Perfume6', 9.0, 390.87);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('GW7S43IC', 'Tshirts', 'Tshirt4', 6.0, 288.78);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('QSD8P4XT', 'Jeans', 'Jeans4', 7.0, 190.47);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('AZ0ZNZ3T', 'Shoes', 'Shoes3', 3.0, 157.05);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('EQLSU8MI', 'Jeans', 'Jeans5', 10.0, 262.0);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('05UVQWFW', 'Shoes', 'Shoes6', 1.0, 41.98);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('1UOAA2QY', 'Smart Phone', 'Phone5', 5.0, 123.95);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('KJ8GVSKO', 'Smart Phone', 'Phone3', 10.0, 476.5);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('MOU3DN1T', 'Jeans', 'Jeans3', 9.0, 452.97);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('XSOA8E5B', 'Shoes', 'Shoes3', 10.0, 294.5);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('OT6ATJ4M', 'Smart Phone', 'Phone2', 1.0, 39.82);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('UGXBRYTI', 'Tshirts', 'Tshirt2', NULL, NULL);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('M9IF826B', 'Perfumes', 'Perfume6', 2.0, 93.72);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('OV5VXA8M', 'Jeans', 'Jeans1', 7.0, 367.71);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('39X6KQB1', 'Shoes', 'Shoes1', 10.0, 305.9);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('F52BWHNY', 'Water bottles', 'Bottle1', 9.0, 388.89);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('8JV7OJMP', 'Tshirts', 'Tshirt2', 5.0, 178.0);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('F2E6WPRL', 'Smart Phone', 'Phone3', 1.0, 38.95);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('VLHWXPBR', 'Smart Phone', 'Phone2', 3.0, 82.68);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('NIPG43TL', 'Smart Phone', 'Phone4', 5.0, 183.1);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('0HF36C0O', 'Smart Phone', 'Phone1', 5.0, 184.85);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('I2F8RPJX', 'Water bottles', 'Bottle2', 2.0, 86.42);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('ZLLGYG4F', 'Water bottles', 'Bottle2', 9.0, 327.6);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('RWQB6TWN', 'Shoes', 'Shoes1', 9.0, 330.3);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('JINH1K50', 'Perfumes', 'Perfume1', 8.0, 286.24);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('MK3UHK6H', 'Water bottles', 'Bottle3', 8.0, 218.4);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('IEHC2YIX', 'Shoes', 'Shoes2', 9.0, 210.06);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('RTG6C2RR', 'Perfumes', 'Perfume2', 1.0, 45.05);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('LCGQLLX7', 'Tshirts', 'Tshirt3', 7.0, 211.68);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('DUDPRK5R', 'Water bottles', 'Bottle2', 9.0, 217.98);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('VO79I3EV', 'Water bottles', 'Bottle4', 7.0, 204.89);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('8MVU2YET', 'Shoes', 'Shoes4', 7.0, 236.32);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('TI7ZFZTO', 'Perfumes', 'Perfume3', 10.0, 227.3);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('KJ71K16Y', 'Perfumes', 'Perfume3', 3.0, 153.75);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('U536LZMS', 'Water bottles', 'Bottle4', 8.0, 237.04);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('GC0QTXXW', 'Perfumes', 'Perfume6', 10.0, 242.6);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('X6QCALUK', 'Tshirts', 'Tshirt2', 9.0, 273.78);
INSERT INTO QatarSales (SaleId, Category, Product, Qty, Sale) VALUES ('P1F99DGH', 'Shoes', 'Shoes3', 5.0, 156.25);
