INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('ES2FX0ZK', 'Tshirts', 'Tshirt4', 10.0, 32.2);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('0KZQVS9J', 'Perfumes', 'Perfume1', 5.0, 15.85);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('0402W29A', 'Jeans', 'Jeans3', 3.0, 15.09);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('OAR4G58O', 'Water bottles', 'Bottle1', 4.0, 12.24);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('EK17M6J3', 'Jeans', 'Jeans4', 9.0, 39.33);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('41J2PATD', 'Smart Phone', 'Phone5', 2.0, 10.9);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('5LP9C5SO', 'Smart Phone', 'Phone1', 5.0, 14.45);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('H0S2UTBT', 'Perfumes', 'Perfume2', 4.0, 9.52);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('NDFWW41F', 'Perfumes', 'Perfume2', 9.0, 27.72);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('88K686QE', 'Perfumes', 'Perfume4', 5.0, 12.65);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('L7W8COF3', 'Shoes', 'Shoes1', 9.0, 49.05);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('VIMI8FO0', 'Jeans', 'Jeans4', 7.0, 28.98);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('Y1AELDWQ', 'Perfumes', 'Perfume6', 8.0, 23.76);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('0QC96MJ9', 'Water bottles', 'Bottle4', 2.0, 9.7);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('V5Y21ID9', 'Smart Phone', 'Phone3', 8.0, 34.48);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('RZPCD140', 'Perfumes', 'Perfume5', 4.0, 21.72);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('49CD3IRV', 'Shoes', 'Shoes6', 7.0, 38.08);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('VUV5YBD4', 'Water bottles', 'Bottle3', 8.0, 39.52);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('MY6PO0M2', 'Water bottles', 'Bottle1', 2.0, 6.84);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('3W1YAUA8', 'Smart Phone', 'Phone5', 1.0, 4.18);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('4J3M9IQB', 'Tshirts', 'Tshirt3', 1.0, 4.45);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('H1TLOM34', 'Smart Phone', 'Phone6', 5.0, 15.25);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('LL6DOWX1', 'Tshirts', 'Tshirt3', 9.0, 30.33);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('MPNFGAGL', 'Jeans', 'Jeans3', 8.0, 31.6);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('TOZHDV5O', 'Perfumes', 'Perfume6', 5.0, 24.7);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('O7D835KU', 'Shoes', 'Shoes2', 9.0, 35.64);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('IF9AIZH5', 'Tshirts', 'Tshirt3', 8.0, 19.92);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('K84RPU9G', 'Smart Phone', 'Phone6', 3.0, 7.05);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('0Z92JN67', 'Jeans', 'Jeans5', 10.0, 41.2);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('49ITE92S', 'Shoes', 'Shoes5', 3.0, 11.43);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('ZZXT9QUB', 'Smart Phone', 'Phone5', 10.0, 33.7);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('8GUUCM5F', 'Perfumes', 'Perfume4', 7.0, 18.2);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('J6AVP1EO', 'Water bottles', 'Bottle3', 5.0, 24.9);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('I2SO19V5', 'Water bottles', 'Bottle4', 5.0, 19.25);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('E9WT00IV', 'Perfumes', 'Perfume1', 6.0, 30.36);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('0LDOZY2N', 'Jeans', 'Jeans2', NULL, NULL);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('LGPJDJHM', 'Smart Phone', 'Phone2', 3.0, 8.25);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('SAV9CNG8', 'Water bottles', 'Bottle6', 8.0, 21.92);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('L2UNCGWR', 'Perfumes', 'Perfume1', NULL, NULL);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('6VU6Z5GF', 'Perfumes', 'Perfume2', 2.0, 11.02);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('3LKMGS6R', 'Smart Phone', 'Phone1', 9.0, 25.83);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('7TNQETMN', 'Perfumes', 'Perfume2', 6.0, 26.64);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('M6736Z4D', 'Jeans', 'Jeans4', 7.0, 17.43);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('UZS1XKE1', 'Perfumes', 'Perfume1', 6.0, 28.68);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('CADUVL91', 'Shoes', 'Shoes6', 7.0, 28.56);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('8LV6TX0T', 'Water bottles', 'Bottle6', 1.0, 3.18);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('B350SGNZ', 'Tshirts', 'Tshirt3', 6.0, 28.98);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('ZCHHXA7H', 'Jeans', 'Jeans1', 3.0, 10.02);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('X6LGOI7O', 'Water bottles', 'Bottle1', 1.0, 3.43);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('J7YZ6L7X', 'Jeans', 'Jeans2', 10.0, 54.5);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('N4G2JAYB', 'Shoes', 'Shoes4', 7.0, 29.75);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('WE6RGL7J', 'Smart Phone', 'Phone2', 4.0, 10.52);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('TKUDE358', 'Water bottles', 'Bottle6', 7.0, 25.48);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('QDI3G13I', 'Perfumes', 'Perfume4', 9.0, 22.23);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('VB71GHLU', 'Perfumes', 'Perfume3', 3.0, 13.14);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('MHXOFKCG', 'Jeans', 'Jeans3', 5.0, 15.6);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('5CITUF8C', 'Jeans', 'Jeans3', 8.0, 19.28);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('WG7NFDIN', 'Water bottles', 'Bottle1', 9.0, 21.42);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('41BTA3RU', 'Perfumes', 'Perfume1', 10.0, 28.6);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('6IRJ9WR6', 'Smart Phone', 'Phone3', 7.0, 30.94);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('K08NJF0P', 'Smart Phone', 'Phone5', 4.0, 11.92);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('ZTIO4M7P', 'Shoes', 'Shoes2', NULL, NULL);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('QMXETIZU', 'Smart Phone', 'Phone4', 8.0, 33.04);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('T1OXHFDX', 'Water bottles', 'Bottle6', 6.0, 26.88);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('M6X7P7AH', 'Shoes', 'Shoes5', 4.0, 13.28);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('XU2FLI01', 'Perfumes', 'Perfume6', 10.0, 30.3);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('05Y2DA5B', 'Smart Phone', 'Phone3', 10.0, 48.0);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('08LCWL6Q', 'Tshirts', 'Tshirt3', 6.0, 19.5);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('2F5FE6OU', 'Shoes', 'Shoes6', 5.0, 13.85);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('9XFQ1ENN', 'Water bottles', 'Bottle4', 5.0, 17.35);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('VG688U59', 'Jeans', 'Jeans1', 6.0, 26.22);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('Y7D78HWK', 'Shoes', 'Shoes1', 10.0, 37.1);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('WV9NJS96', 'Tshirts', 'Tshirt3', 8.0, 18.96);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('XZJ9MJ9X', 'Tshirts', 'Tshirt4', 3.0, 7.62);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('57AUKHQN', 'Water bottles', 'Bottle1', 1.0, 2.91);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('NS9PZEMJ', 'Water bottles', 'Bottle6', 7.0, 27.16);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('7DXLSE33', 'Jeans', 'Jeans4', 2.0, 8.84);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('F225AA35', 'Tshirts', 'Tshirt2', 6.0, 15.6);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('52DEZH0C', 'Perfumes', 'Perfume1', 8.0, 42.16);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('2IBCLTRH', 'Tshirts', 'Tshirt6', 1.0, 4.34);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('0V4PSC9J', 'Smart Phone', 'Phone5', 8.0, 29.2);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('G41IO4KO', 'Perfumes', 'Perfume5', 2.0, 5.3);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('0TX8J1CC', 'Water bottles', 'Bottle3', 5.0, 19.6);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('Y6Q9YL16', 'Shoes', 'Shoes6', 7.0, 18.69);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('J4Q0RR1L', 'Water bottles', 'Bottle6', 2.0, 9.96);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('YO5L28O5', 'Water bottles', 'Bottle2', 3.0, 7.5);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('852N5FNP', 'Smart Phone', 'Phone4', 7.0, 29.89);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('DOFMAOK8', 'Water bottles', 'Bottle2', 3.0, 9.96);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('0P8F8C8C', 'Perfumes', 'Perfume3', 8.0, 41.28);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('I72OALFW', 'Shoes', 'Shoes6', 5.0, 14.8);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('EK035N8C', 'Water bottles', 'Bottle5', 2.0, 10.24);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('Y66W6RKM', 'Smart Phone', 'Phone3', 4.0, 15.36);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('2U6ZV3IU', 'Shoes', 'Shoes6', 3.0, 11.43);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('1WCRV68J', 'Tshirts', 'Tshirt3', 2.0, 8.22);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('N1RIAMWU', 'Smart Phone', 'Phone4', 5.0, 14.85);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('5H3G7VKC', 'Shoes', 'Shoes3', 6.0, 30.9);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('2P3AJFAX', 'Jeans', 'Jeans5', 5.0, 17.35);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('WTV1DJJZ', 'Smart Phone', 'Phone1', 3.0, 13.2);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('8E5TNLZT', 'Smart Phone', 'Phone3', 3.0, 11.46);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('L4BKUU5C', 'Water bottles', 'Bottle4', 7.0, 21.98);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('FDFZDMMC', 'Water bottles', 'Bottle6', 2.0, 5.24);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('SXOF33QE', 'Shoes', 'Shoes1', 9.0, 23.31);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('B4IBHIF5', 'Shoes', 'Shoes2', 9.0, 21.69);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('SKAZOCHB', 'Perfumes', 'Perfume3', 7.0, 16.73);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('UN6FHT60', 'Jeans', 'Jeans5', 6.0, 16.08);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('FHVMLJEK', 'Shoes', 'Shoes3', 9.0, 37.17);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('HEND7H10', 'Tshirts', 'Tshirt4', 9.0, 37.89);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('MBWU5JSL', 'Shoes', 'Shoes6', 10.0, 37.3);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('8NL9VFRU', 'Jeans', 'Jeans2', 4.0, 18.6);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('W54W487K', 'Shoes', 'Shoes6', 4.0, 10.64);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('BHGP5CPA', 'Smart Phone', 'Phone6', 3.0, 8.28);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('752H70YB', 'Tshirts', 'Tshirt1', 5.0, 22.25);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('0Q5ZJAUC', 'Smart Phone', 'Phone2', NULL, NULL);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('NBPQGA6X', 'Water bottles', 'Bottle2', 7.0, 38.43);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('2AJ5IQAX', 'Shoes', 'Shoes6', 8.0, 26.0);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('Z0KDN3TN', 'Perfumes', 'Perfume4', 8.0, 27.12);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('0MGOQMK3', 'Shoes', 'Shoes6', 3.0, 11.43);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('DJE7XQTY', 'Smart Phone', 'Phone6', 6.0, 25.98);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('MW04U923', 'Tshirts', 'Tshirt3', 3.0, 15.36);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('TSUJT70Y', 'Smart Phone', 'Phone1', 2.0, 9.32);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('7S3HMO1D', 'Shoes', 'Shoes4', 6.0, 29.28);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('682R6ZL1', 'Water bottles', 'Bottle6', 4.0, 9.2);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('ABEG1CJ8', 'Shoes', 'Shoes2', 2.0, 6.4);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('KNHPVRWB', 'Smart Phone', 'Phone3', 1.0, 5.11);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('JR211PV5', 'Smart Phone', 'Phone1', 6.0, 14.64);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('81DJDI3W', 'Water bottles', 'Bottle4', 7.0, 17.36);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('VQLTZQWD', 'Tshirts', 'Tshirt4', 6.0, 20.64);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('PSQZN7XB', 'Water bottles', 'Bottle2', 1.0, 4.68);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('6KFKLDF4', 'Perfumes', 'Perfume1', 8.0, 24.96);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('1361BGMY', 'Jeans', 'Jeans4', 1.0, 4.12);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('FE9VAR2P', 'Smart Phone', 'Phone2', 2.0, 5.54);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('TPBPZCD5', 'Water bottles', 'Bottle5', 6.0, 31.74);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('65EFUXQ9', 'Water bottles', 'Bottle3', 9.0, 31.05);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('GOUIFEZA', 'Shoes', 'Shoes5', 2.0, 10.78);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('XVA5E742', 'Tshirts', 'Tshirt5', 2.0, 9.54);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('DNWT2FES', 'Jeans', 'Jeans6', 8.0, 26.48);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('FWOW73O1', 'Tshirts', 'Tshirt4', 2.0, 9.92);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('Y7OV50EW', 'Tshirts', 'Tshirt3', 1.0, 3.21);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('VK1PBCD6', 'Perfumes', 'Perfume4', 3.0, 10.32);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('OQ37KTLL', 'Jeans', 'Jeans6', NULL, NULL);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('7VXUQDRM', 'Smart Phone', 'Phone5', 10.0, 49.4);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('JJKSL66U', 'Perfumes', 'Perfume5', 5.0, 26.3);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('YKVYGW22', 'Shoes', 'Shoes3', 6.0, 28.44);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('THQSE0KI', 'Water bottles', 'Bottle3', 6.0, 29.1);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('3NOZ7QMJ', 'Perfumes', 'Perfume6', 3.0, 16.05);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('9AG77Q9V', 'Tshirts', 'Tshirt3', 7.0, 34.23);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('BP9VRNEG', 'Shoes', 'Shoes5', 4.0, 14.2);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('JTJ27YH6', 'Shoes', 'Shoes1', NULL, NULL);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('9ZKIHV17', 'Perfumes', 'Perfume1', NULL, NULL);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('LH33HW8D', 'Shoes', 'Shoes2', 9.0, 45.45);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('EIOIV67K', 'Water bottles', 'Bottle5', 5.0, 22.95);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('44QI4OPF', 'Tshirts', 'Tshirt2', 7.0, 35.21);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('1HYP5MAS', 'Smart Phone', 'Phone5', 1.0, 4.85);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('ZVZN2HLO', 'Smart Phone', 'Phone4', 6.0, 17.88);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('VQA7IZQ2', 'Jeans', 'Jeans6', 4.0, 16.32);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('R06DJIN9', 'Smart Phone', 'Phone5', 7.0, 16.73);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('STHBNBIZ', 'Smart Phone', 'Phone2', 10.0, 53.4);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('JSJFFP5G', 'Jeans', 'Jeans1', 9.0, 22.77);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('5WU2550K', 'Smart Phone', 'Phone3', 2.0, 6.78);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('3HZCD3GE', 'Smart Phone', 'Phone4', 4.0, 9.52);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('TG2LGJ3S', 'Smart Phone', 'Phone5', 3.0, 9.06);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('FE54UKIG', 'Tshirts', 'Tshirt4', 1.0, 4.51);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('CNAQ2YOT', 'Tshirts', 'Tshirt6', 10.0, 25.0);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('2U4OJ7G4', 'Smart Phone', 'Phone5', 9.0, 35.64);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('4E6NKAR1', 'Jeans', 'Jeans1', 10.0, 40.3);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('520XKIAI', 'Jeans', 'Jeans4', 3.0, 13.26);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('NHE8IFXD', 'Smart Phone', 'Phone3', 8.0, 35.92);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('5CK3TB94', 'Shoes', 'Shoes1', 7.0, 37.66);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('F9FZJAHS', 'Tshirts', 'Tshirt3', 5.0, 23.4);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('MLN2V51P', 'Tshirts', 'Tshirt4', 10.0, 44.7);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('S9F3LZ0W', 'Perfumes', 'Perfume1', 9.0, 44.64);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('WJHBAEPG', 'Jeans', 'Jeans2', 4.0, 10.96);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('AC4JRCQ9', 'Jeans', 'Jeans4', 5.0, 16.45);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('W948JU63', 'Water bottles', 'Bottle4', 8.0, 31.28);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('Y4VY32I3', 'Shoes', 'Shoes6', 9.0, 27.27);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('R0O8K5DF', 'Smart Phone', 'Phone4', 9.0, 33.39);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('67ZSOOUK', 'Jeans', 'Jeans2', 4.0, 17.92);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('7COPO9MN', 'Jeans', 'Jeans2', 2.0, 7.56);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('VO4KVFFL', 'Shoes', 'Shoes2', 8.0, 33.28);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('FP672ZFB', 'Smart Phone', 'Phone1', 2.0, 4.68);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('9NY3MUB6', 'Smart Phone', 'Phone2', NULL, NULL);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('CBA7263R', 'Shoes', 'Shoes1', NULL, NULL);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('3KCVJXZD', 'Shoes', 'Shoes5', 9.0, 23.76);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('4XZ3MSKZ', 'Perfumes', 'Perfume2', 1.0, 4.15);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('XHQZBC5F', 'Smart Phone', 'Phone4', 4.0, 15.0);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('1YUZPEX7', 'Smart Phone', 'Phone2', 2.0, 7.26);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('XNOMB42O', 'Perfumes', 'Perfume6', 4.0, 18.12);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('Q30ZX815', 'Smart Phone', 'Phone4', 7.0, 26.74);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('OR9F5IV8', 'Jeans', 'Jeans1', 3.0, 10.44);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('WZ2NAR3S', 'Jeans', 'Jeans6', 1.0, 2.34);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('T69WWP82', 'Jeans', 'Jeans2', 9.0, 32.31);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('9QKAV8C3', 'Smart Phone', 'Phone6', 5.0, 24.15);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('ILVQKXBI', 'Smart Phone', 'Phone4', 10.0, 49.9);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('IH3IABC2', 'Perfumes', 'Perfume3', 1.0, 4.8);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('50121XRU', 'Perfumes', 'Perfume5', 1.0, 4.66);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('7O0GXAPL', 'Perfumes', 'Perfume6', 2.0, 6.8);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('70GKJFP0', 'Jeans', 'Jeans4', NULL, NULL);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('9YXCFE78', 'Shoes', 'Shoes1', 5.0, 18.75);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('MS4TSRW2', 'Tshirts', 'Tshirt3', 2.0, 8.84);
INSERT INTO OmanSales (SaleId, Category, Product, Qty, Sale) VALUES ('TJA622DC', 'Shoes', 'Shoes1', 7.0, 22.33);
