INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('A5XIN9DL', 'Water bottles', 'Bottle3', 6.0, 450.72);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('8UZB7KR0', 'Perfumes', 'Perfume5', 4.0, 498.52);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('K99JCJN9', 'Tshirts', 'Tshirt3', 6.0, 842.34);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('MOE0SY5Y', 'Tshirts', 'Tshirt5', 4.0, 322.68);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('6LTHET25', 'Smart Phone', 'Phone2', 7.0, 706.02);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('P61XUFCT', 'Shoes', 'Shoes6', 9.0, 707.13);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('15OOP767', 'Water bottles', 'Bottle1', 3.0, 195.81);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('G1WJUIIY', 'Shoes', 'Shoes2', 2.0, 156.16);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('SVZN4REG', 'Shoes', 'Shoes1', 8.0, 627.6);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('8IYHHG8P', 'Tshirts', 'Tshirt4', 1.0, 95.57);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('P1V3ZO7U', 'Perfumes', 'Perfume4', 8.0, 740.88);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('DQ55IT9B', 'Perfumes', 'Perfume5', 1.0, 127.22);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('KOK3QPWB', 'Smart Phone', 'Phone5', 1.0, 85.47);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('0E27ZEOQ', 'Perfumes', 'Perfume2', 8.0, 583.28);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('DLXZF0DZ', 'Jeans', 'Jeans4', 4.0, 475.36);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('WFTBGM55', 'Water bottles', 'Bottle3', 7.0, 881.93);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('L08KG68A', 'Jeans', 'Jeans2', 1.0, 114.41);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('3VRHXQPV', 'Shoes', 'Shoes1', 8.0, 1040.4);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('W3HGBMFB', 'Tshirts', 'Tshirt2', 5.0, 698.3);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('D9FKXZUU', 'Perfumes', 'Perfume5', 2.0, 135.46);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('1L6314CQ', 'Smart Phone', 'Phone6', 1.0, 73.28);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('OHHCU9TD', 'Tshirts', 'Tshirt6', 6.0, 767.76);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('VLS9MEUS', 'Water bottles', 'Bottle6', 5.0, 576.95);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('IKGEQ20H', 'Water bottles', 'Bottle4', 3.0, 415.26);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('UWAHK2LS', 'Perfumes', 'Perfume4', 6.0, 634.02);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('OU83G47R', 'Shoes', 'Shoes1', 6.0, 627.36);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('W6TM2O04', 'Smart Phone', 'Phone1', 8.0, 649.28);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('THY25M8K', 'Shoes', 'Shoes5', 6.0, 789.18);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('UOV51ZLB', 'Tshirts', 'Tshirt3', 9.0, 741.51);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('Q8HKE226', 'Smart Phone', 'Phone1', 4.0, 433.48);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('6FMR5LL1', 'Smart Phone', 'Phone5', NULL, NULL);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('0QZSA7YV', 'Tshirts', 'Tshirt5', 3.0, 262.32);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('SXLUL6LG', 'Tshirts', 'Tshirt3', 1.0, 74.51);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('EFJAWSHM', 'Shoes', 'Shoes5', 8.0, 1169.44);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('ICWMPEQY', 'Shoes', 'Shoes3', 5.0, 669.35);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('GVV4ZWL3', 'Tshirts', 'Tshirt4', 7.0, 776.72);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('UD2ZDLX1', 'Water bottles', 'Bottle6', 2.0, 240.4);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('JNG7L4LR', 'Smart Phone', 'Phone2', 3.0, 417.87);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('4KMUSOZD', 'Tshirts', 'Tshirt4', 8.0, 957.6);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('QVIIFRCH', 'Perfumes', 'Perfume6', 5.0, 643.45);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('2TIXC7UR', 'Water bottles', 'Bottle5', 7.0, 931.0);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('3G8CD31N', 'Perfumes', 'Perfume5', 9.0, 663.93);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('356WAFFT', 'Smart Phone', 'Phone6', 2.0, 177.84);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('YLU6K7P9', 'Smart Phone', 'Phone5', 4.0, 349.76);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('OEKNTBZ3', 'Shoes', 'Shoes1', 10.0, 1258.6);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('PVWZOPHG', 'Shoes', 'Shoes1', 1.0, 91.13);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('F9YECAZR', 'Jeans', 'Jeans2', 6.0, 684.96);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('6Z7WQP3N', 'Smart Phone', 'Phone2', 7.0, 832.79);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('R0ZJ7UBB', 'Jeans', 'Jeans2', 1.0, 134.36);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('8C0S41KS', 'Smart Phone', 'Phone6', 10.0, 1222.9);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('08CW2LBM', 'Perfumes', 'Perfume5', 8.0, 1128.08);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('0P82KB70', 'Tshirts', 'Tshirt4', 8.0, 1070.96);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('GB93WKCS', 'Water bottles', 'Bottle5', 8.0, 1075.84);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('4AEGVFQ3', 'Shoes', 'Shoes3', 5.0, 480.9);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('5MDF7FR9', 'Shoes', 'Shoes6', 3.0, 384.24);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('U4BJ3BQR', 'Smart Phone', 'Phone2', 3.0, 264.15);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('NZRF5A7Q', 'Smart Phone', 'Phone6', 9.0, 819.09);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('7W8P74MJ', 'Water bottles', 'Bottle3', 1.0, 73.77);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('100VHMYG', 'Tshirts', 'Tshirt3', 7.0, 837.9);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('OSYM0JBW', 'Perfumes', 'Perfume1', 2.0, 126.1);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('WZE4EX6U', 'Tshirts', 'Tshirt5', 4.0, 548.28);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('Q7W7JP61', 'Jeans', 'Jeans1', 5.0, 493.25);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('1NLC8JPR', 'Shoes', 'Shoes3', 2.0, 192.86);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('F1HX6ZDC', 'Jeans', 'Jeans5', 8.0, 602.0);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('6FX7XJZ6', 'Perfumes', 'Perfume6', 8.0, 511.36);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('P422TA83', 'Perfumes', 'Perfume1', 8.0, 974.4);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('YOW8DT8C', 'Smart Phone', 'Phone1', 6.0, 621.42);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('BNGZ6WMD', 'Smart Phone', 'Phone3', 3.0, 394.2);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('GZVRCTLT', 'Water bottles', 'Bottle4', 3.0, 198.03);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('MZOHXS75', 'Smart Phone', 'Phone1', NULL, NULL);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('BFXQ7BZE', 'Perfumes', 'Perfume2', 4.0, 282.28);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('3DW4C3EV', 'Jeans', 'Jeans6', NULL, NULL);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('M40OEYTL', 'Perfumes', 'Perfume2', 4.0, 461.08);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('EFOZTP7B', 'Jeans', 'Jeans1', 6.0, 416.76);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('5CA7ZVKY', 'Tshirts', 'Tshirt6', 3.0, 190.65);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('JQIGYVZW', 'Smart Phone', 'Phone6', 3.0, 426.72);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('PUG99W59', 'Tshirts', 'Tshirt6', 5.0, 527.1);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('BEF46RF7', 'Perfumes', 'Perfume2', 4.0, 385.72);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('JW6QDBTF', 'Tshirts', 'Tshirt6', 4.0, 465.52);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('ZVLHYL2L', 'Tshirts', 'Tshirt4', 2.0, 182.26);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('6CVBPHVG', 'Tshirts', 'Tshirt2', 4.0, 435.48);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('MJMBUKDQ', 'Shoes', 'Shoes2', 4.0, 565.04);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('V2WWG84D', 'Smart Phone', 'Phone2', 4.0, 395.08);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('RQAP5IPI', 'Perfumes', 'Perfume4', 4.0, 544.32);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('9BQ1BTR2', 'Perfumes', 'Perfume2', 1.0, 114.16);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('1YOHMI9A', 'Tshirts', 'Tshirt4', 2.0, 263.8);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('0AQ15O2N', 'Water bottles', 'Bottle3', 8.0, 1068.0);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('6LBPJ8T2', 'Smart Phone', 'Phone6', 2.0, 220.2);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('S6NBNQBN', 'Water bottles', 'Bottle1', 6.0, 410.82);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('EMTX015Z', 'Water bottles', 'Bottle5', 9.0, 785.88);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('YJCMRSEZ', 'Water bottles', 'Bottle2', 5.0, 625.0);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('NYY95G5D', 'Water bottles', 'Bottle5', 8.0, 1118.24);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('FEFFH8AO', 'Smart Phone', 'Phone2', 2.0, 150.5);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('P0AGA24S', 'Water bottles', 'Bottle5', 8.0, 842.4);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('VZ4QKE2G', 'Shoes', 'Shoes4', 6.0, 736.68);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('FK8WFTGG', 'Shoes', 'Shoes2', 5.0, 337.45);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('IBLEJGUB', 'Water bottles', 'Bottle6', 3.0, 245.7);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('9TEA7187', 'Shoes', 'Shoes3', 8.0, 1036.48);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('LZRK79UF', 'Jeans', 'Jeans1', 9.0, 1129.41);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('Y06FTLO4', 'Perfumes', 'Perfume6', 8.0, 833.52);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('XVH7KATQ', 'Smart Phone', 'Phone3', 1.0, 138.18);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('RVSCYOZP', 'Water bottles', 'Bottle1', 7.0, 602.56);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('M95D0P92', 'Smart Phone', 'Phone3', NULL, NULL);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('FVDHR59C', 'Shoes', 'Shoes2', 7.0, 796.53);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('6OUZ1EGN', 'Perfumes', 'Perfume4', 7.0, 994.84);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('4KUQAAJ8', 'Perfumes', 'Perfume4', NULL, NULL);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('G6XB1R8V', 'Water bottles', 'Bottle4', 5.0, 570.8);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('WRYESU4F', 'Shoes', 'Shoes5', 7.0, 658.63);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('FJP6MKT7', 'Tshirts', 'Tshirt2', 3.0, 319.59);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('VGLL42JZ', 'Perfumes', 'Perfume2', 3.0, 220.2);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('ASNRM6DF', 'Shoes', 'Shoes1', 6.0, 478.08);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('Y84ZZ2P6', 'Jeans', 'Jeans2', 9.0, 1250.28);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('LN36V1MZ', 'Tshirts', 'Tshirt2', 8.0, 843.36);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('4FIEECY2', 'Tshirts', 'Tshirt6', 4.0, 310.84);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('HBXVQ6BK', 'Tshirts', 'Tshirt1', 7.0, 468.09);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('VHYBF0JU', 'Tshirts', 'Tshirt1', 10.0, 874.4);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('SC31TZ8G', 'Shoes', 'Shoes2', 10.0, 920.0);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('74RZGYD4', 'Perfumes', 'Perfume1', 2.0, 177.1);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('E9EDE1ZU', 'Smart Phone', 'Phone4', 4.0, 451.72);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('KVL9PTK4', 'Tshirts', 'Tshirt1', 2.0, 220.2);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('NAYYOSYE', 'Jeans', 'Jeans1', 8.0, 1177.36);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('C9MV9E40', 'Smart Phone', 'Phone4', 2.0, 165.52);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('127MY89S', 'Shoes', 'Shoes6', 10.0, 959.4);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('RWEDBCY8', 'Jeans', 'Jeans4', 5.0, 616.4);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('WDC112HX', 'Smart Phone', 'Phone5', 3.0, 299.25);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('T8BP6NLN', 'Smart Phone', 'Phone5', 6.0, 778.08);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('X25FPLO1', 'Smart Phone', 'Phone1', NULL, NULL);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('UR4SOR8W', 'Perfumes', 'Perfume6', 9.0, 1166.04);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('B4M0A6MD', 'Shoes', 'Shoes3', 1.0, 135.96);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('IILDY5EG', 'Shoes', 'Shoes3', 1.0, 144.95);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('5U6JZV9N', 'Perfumes', 'Perfume3', NULL, NULL);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('YHR3YFK8', 'Smart Phone', 'Phone3', 8.0, 593.12);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('HJKU2W8Z', 'Jeans', 'Jeans4', 2.0, 258.12);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('UTPMC3SK', 'Perfumes', 'Perfume1', 5.0, 349.75);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('JSYT5WSG', 'Water bottles', 'Bottle5', 7.0, 785.33);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('7TW1PUWS', 'Smart Phone', 'Phone2', 8.0, 762.56);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('4O46W4JK', 'Shoes', 'Shoes4', 3.0, 298.14);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('IFA2LR9P', 'Jeans', 'Jeans3', 4.0, 450.72);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('J2XG48RA', 'Tshirts', 'Tshirt2', 3.0, 195.45);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('6Y5O44IU', 'Tshirts', 'Tshirt3', 2.0, 225.62);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('J5IE3LVO', 'Perfumes', 'Perfume1', 10.0, 1277.1);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('FG8PJVRN', 'Water bottles', 'Bottle6', 7.0, 623.28);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('IJ2FRNLX', 'Tshirts', 'Tshirt3', 8.0, 1181.28);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('ITL8N3E5', 'Perfumes', 'Perfume1', 1.0, 146.18);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('77K71K4F', 'Smart Phone', 'Phone4', NULL, NULL);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('JC2R07LP', 'Smart Phone', 'Phone6', 7.0, 460.32);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('MV30QABX', 'Tshirts', 'Tshirt2', 9.0, 628.47);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('OWLCFS83', 'Water bottles', 'Bottle4', 3.0, 185.85);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('R0JY32HO', 'Jeans', 'Jeans5', 6.0, 710.82);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('AAUWIDQJ', 'Jeans', 'Jeans4', 10.0, 897.8);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('JDN8EZP7', 'Jeans', 'Jeans1', 7.0, 960.33);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('G52KRE4V', 'Smart Phone', 'Phone6', 4.0, 348.76);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('OFKJW6NY', 'Shoes', 'Shoes6', 7.0, 589.68);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('59OHNPVC', 'Smart Phone', 'Phone1', NULL, NULL);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('6978V0BJ', 'Perfumes', 'Perfume1', 4.0, 483.76);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('N8UUJS75', 'Perfumes', 'Perfume4', 7.0, 1023.26);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('FEBE5407', 'Jeans', 'Jeans1', 9.0, 1045.17);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('L6L91F4X', 'Shoes', 'Shoes3', 5.0, 633.6);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('GQFQE6RP', 'Smart Phone', 'Phone1', 1.0, 90.52);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('45ED5GGS', 'Water bottles', 'Bottle5', 8.0, 605.92);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('V8SUOC1Y', 'Shoes', 'Shoes5', 10.0, 883.0);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('N7DLBQZR', 'Shoes', 'Shoes1', 2.0, 222.42);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('8X8L008U', 'Water bottles', 'Bottle3', 1.0, 103.08);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('20TVDJI1', 'Jeans', 'Jeans1', 5.0, 511.1);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('F2K1XERP', 'Smart Phone', 'Phone1', NULL, NULL);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('DNHQNJVD', 'Shoes', 'Shoes6', 6.0, 872.64);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('PBMQIYFR', 'Smart Phone', 'Phone3', 7.0, 987.07);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('P6RFE64S', 'Water bottles', 'Bottle6', 5.0, 602.85);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('7SSOQZ3M', 'Shoes', 'Shoes5', NULL, NULL);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('0Q24BOZL', 'Perfumes', 'Perfume1', 1.0, 75.86);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('3M73HC9J', 'Water bottles', 'Bottle4', 8.0, 1121.2);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('OAXQOX00', 'Water bottles', 'Bottle1', 1.0, 62.19);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('Y8Y2DEG3', 'Shoes', 'Shoes5', 10.0, 1070.2);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('XXPW2GKQ', 'Water bottles', 'Bottle2', 4.0, 488.68);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('60QRAQIK', 'Smart Phone', 'Phone4', NULL, NULL);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('4PORU09B', 'Smart Phone', 'Phone1', 2.0, 282.02);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('65ICAUTJ', 'Smart Phone', 'Phone4', 10.0, 1470.4);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('WXQPF0QP', 'Water bottles', 'Bottle4', 2.0, 247.78);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('4ZQ50OP7', 'Perfumes', 'Perfume2', 6.0, 824.64);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('WK0YEHVD', 'Water bottles', 'Bottle6', 8.0, 655.2);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('BA5MF36B', 'Smart Phone', 'Phone4', 4.0, 527.08);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('EIJMMB5J', 'Tshirts', 'Tshirt3', 10.0, 901.5);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('DB828192', 'Jeans', 'Jeans6', 10.0, 1459.4);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('DW56FKPS', 'Perfumes', 'Perfume1', 1.0, 125.49);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('3EH81A4R', 'Water bottles', 'Bottle1', 6.0, 622.14);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('ZOWI1T2E', 'Shoes', 'Shoes5', 5.0, 542.5);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('2NBFA37D', 'Smart Phone', 'Phone4', 8.0, 1012.8);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('C1XX6CWZ', 'Shoes', 'Shoes4', 3.0, 348.78);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('5Z5ZLM36', 'Water bottles', 'Bottle5', 7.0, 785.33);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('HT2XZ52O', 'Perfumes', 'Perfume2', 8.0, 1141.84);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('OZ5STHSL', 'Jeans', 'Jeans3', 9.0, 933.21);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('VI109DCN', 'Shoes', 'Shoes6', 1.0, 129.56);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('7QUAMI0U', 'Water bottles', 'Bottle5', 1.0, 143.6);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('MK2ZYZSI', 'Water bottles', 'Bottle6', 10.0, 910.1);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('DZ3CC5RQ', 'Shoes', 'Shoes5', 6.0, 713.04);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('SOJRPP7R', 'Shoes', 'Shoes6', 10.0, 1320.2);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('ZEZ5EHR0', 'Smart Phone', 'Phone2', 3.0, 367.98);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('4DNKSEKN', 'Perfumes', 'Perfume3', 2.0, 274.88);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('FVB66H3R', 'Shoes', 'Shoes4', NULL, NULL);
INSERT INTO NorwaySales (SaleId, Category, Product, Qty, Sale) VALUES ('RLQMN44E', 'Tshirts', 'Tshirt5', 1.0, 114.16);
