INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('IFD0TVBD', 'Water bottles', 'Bottle1', NULL, NULL);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('ZZPQK51F', 'Jeans', 'Jeans5', 9.0, 6327.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('DNMMJBQE', 'Smart Phone', 'Phone3', 4.0, 3376.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('UZBIKCID', 'Smart Phone', 'Phone1', 10.0, 8700.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('NHJ7XVG0', 'Shoes', 'Shoes4', 6.0, 3996.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('Y41IBLJH', 'Jeans', 'Jeans4', 9.0, 6516.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('5XFF0T0P', 'Perfumes', 'Perfume6', 8.0, 7240.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('R14FFYVN', 'Perfumes', 'Perfume4', 3.0, 3063.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('YE511MKF', 'Perfumes', 'Perfume4', 9.0, 4599.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('1SDW4SHN', 'Tshirts', 'Tshirt6', 5.0, 5060.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('VREN93II', 'Jeans', 'Jeans5', 9.0, 4500.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('9TEX8FSV', 'Perfumes', 'Perfume1', 8.0, 4560.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('OYN6QICA', 'Jeans', 'Jeans5', 4.0, 3276.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('ZCCBLSKR', 'Perfumes', 'Perfume2', 1.0, 572.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('R23GDPPQ', 'Perfumes', 'Perfume2', 10.0, 10900.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('OM5IGQPK', 'Water bottles', 'Bottle1', 2.0, 1124.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('B94874FR', 'Jeans', 'Jeans1', 9.0, 5400.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('AO72KZ02', 'Jeans', 'Jeans4', 3.0, 2664.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('HC0CLBR7', 'Water bottles', 'Bottle6', 4.0, 3212.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('4CC5O7UU', 'Perfumes', 'Perfume2', 9.0, 5238.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('S7HZIOYK', 'Tshirts', 'Tshirt5', 10.0, 10780.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('99CHJ755', 'Shoes', 'Shoes1', NULL, NULL);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('W9XA3KX7', 'Shoes', 'Shoes3', 9.0, 7281.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('FKHMY4SJ', 'Jeans', 'Jeans3', 2.0, 2132.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('A1WJ0TPA', 'Tshirts', 'Tshirt1', 5.0, 2725.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('4UFEL624', 'Tshirts', 'Tshirt6', 9.0, 4824.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('25OWF759', 'Shoes', 'Shoes2', 2.0, 1724.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('2OY0IFZN', 'Jeans', 'Jeans4', NULL, NULL);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('K2IAGL58', 'Tshirts', 'Tshirt4', 8.0, 6864.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('9T7E8G8J', 'Shoes', 'Shoes3', 7.0, 8365.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('VSNUJZA7', 'Tshirts', 'Tshirt5', 6.0, 5676.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('P87WXE6S', 'Perfumes', 'Perfume6', 4.0, 3488.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('EP7Y6WKT', 'Water bottles', 'Bottle4', 5.0, 5335.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('VLPYS280', 'Tshirts', 'Tshirt3', 7.0, 7651.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('D8IL3FB9', 'Water bottles', 'Bottle1', 10.0, 8430.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('ZNOFY645', 'Perfumes', 'Perfume1', 10.0, 6990.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('BI4Q2Y9V', 'Smart Phone', 'Phone2', 9.0, 8775.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('3T60RJIW', 'Smart Phone', 'Phone5', 9.0, 8424.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('CKJLTEIY', 'Perfumes', 'Perfume4', 5.0, 4750.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('TOHP6VZ4', 'Water bottles', 'Bottle2', 7.0, 5866.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('148P0TVH', 'Perfumes', 'Perfume4', 6.0, 4830.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('MYOFQEWA', 'Jeans', 'Jeans3', 1.0, 898.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('XEQBNHL1', 'Smart Phone', 'Phone5', 1.0, 585.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('4Q0B8IC8', 'Smart Phone', 'Phone3', 7.0, 5306.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('WIRE8QJN', 'Tshirts', 'Tshirt1', 4.0, 2080.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('8DALY8OZ', 'Perfumes', 'Perfume5', 2.0, 1334.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('ZKY22UBT', 'Tshirts', 'Tshirt5', 4.0, 2416.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('43D8W3ZP', 'Water bottles', 'Bottle3', 6.0, 3072.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('3TRP0J43', 'Water bottles', 'Bottle5', 5.0, 5650.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('UYMRLRMJ', 'Tshirts', 'Tshirt3', 4.0, 3900.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('A8DZR1YX', 'Shoes', 'Shoes5', 5.0, 5345.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('HYLURTP0', 'Smart Phone', 'Phone4', 2.0, 1602.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('JEGET1GH', 'Shoes', 'Shoes3', 5.0, 4065.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('KDGIGATJ', 'Smart Phone', 'Phone3', 9.0, 9999.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('5R5UQPGB', 'Tshirts', 'Tshirt5', 3.0, 3459.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('CWBFUK9E', 'Smart Phone', 'Phone1', 7.0, 7021.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('1N6KVPUC', 'Smart Phone', 'Phone5', 10.0, 7310.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('HXFGCAQV', 'Water bottles', 'Bottle1', 4.0, 4560.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('CIJ2V2HE', 'Shoes', 'Shoes1', 5.0, 4820.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('CFL0UKEY', 'Jeans', 'Jeans6', 5.0, 3225.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('RCBPLJD8', 'Water bottles', 'Bottle4', 9.0, 9468.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('B1QX6GVW', 'Perfumes', 'Perfume5', 5.0, 5450.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('LDFORXO1', 'Smart Phone', 'Phone1', 7.0, 5887.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('E153A5QB', 'Tshirts', 'Tshirt4', 5.0, 4155.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('PBJEK5RB', 'Perfumes', 'Perfume3', 8.0, 9120.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('TTD96QE3', 'Water bottles', 'Bottle5', 3.0, 2454.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('49ITN7S5', 'Smart Phone', 'Phone6', 5.0, 4625.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('7S3KKV9R', 'Tshirts', 'Tshirt3', 7.0, 5936.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('TTQLGZUI', 'Jeans', 'Jeans4', 6.0, 5040.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('NX39RBSV', 'Smart Phone', 'Phone1', 8.0, 7120.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('0OXFQ8MY', 'Tshirts', 'Tshirt4', 8.0, 4120.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('8W5RTWIY', 'Water bottles', 'Bottle1', 9.0, 8001.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('1ZDFKBLC', 'Shoes', 'Shoes2', 7.0, 4200.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('OYGGVNYR', 'Shoes', 'Shoes3', 4.0, 4172.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('JA26YFPM', 'Perfumes', 'Perfume2', 5.0, 4850.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('QK94DNMK', 'Perfumes', 'Perfume3', 7.0, 5292.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('OA529603', 'Water bottles', 'Bottle3', NULL, NULL);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('WWYZX4W6', 'Shoes', 'Shoes2', 6.0, 4344.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('U0DK0GET', 'Water bottles', 'Bottle1', 8.0, 4272.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('J3R30ME8', 'Shoes', 'Shoes5', 5.0, 3340.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('N2ATQYYV', 'Jeans', 'Jeans2', 7.0, 7490.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('A5U6HC36', 'Water bottles', 'Bottle3', 4.0, 3928.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('8KRD5EQY', 'Shoes', 'Shoes6', 3.0, 1638.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('0FODRO8B', 'Water bottles', 'Bottle6', 7.0, 7707.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('DYT9MOGE', 'Shoes', 'Shoes2', 4.0, 3484.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('BM92H3TV', 'Smart Phone', 'Phone1', 10.0, 5210.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('J99T2D5E', 'Jeans', 'Jeans3', 10.0, 5020.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('JEPECQNV', 'Shoes', 'Shoes2', 1.0, 678.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('06XKXB94', 'Smart Phone', 'Phone5', 10.0, 5440.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('6LFEWVZN', 'Smart Phone', 'Phone6', 8.0, 4600.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('P2EX5T5P', 'Perfumes', 'Perfume5', 9.0, 10071.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('ODPXNF7C', 'Jeans', 'Jeans4', 8.0, 7264.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('UVULEMX1', 'Tshirts', 'Tshirt1', 6.0, 3798.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('MUHXID4N', 'Water bottles', 'Bottle1', 10.0, 8190.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('93WXA73J', 'Shoes', 'Shoes5', 7.0, 7518.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('MGFXC08D', 'Jeans', 'Jeans3', 5.0, 4235.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('FLL7V5F1', 'Perfumes', 'Perfume2', 8.0, 6792.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('PVOHSMDY', 'Tshirts', 'Tshirt6', 8.0, 9416.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('H9BH811K', 'Perfumes', 'Perfume4', 5.0, 2730.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('ETIUYMO0', 'Tshirts', 'Tshirt1', 7.0, 4753.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('UUZPEAL2', 'Smart Phone', 'Phone1', 2.0, 1640.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('PDPOC50H', 'Perfumes', 'Perfume4', 6.0, 3540.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('S6M033IF', 'Jeans', 'Jeans1', 2.0, 2086.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('8WQUUY5X', 'Jeans', 'Jeans2', 2.0, 1362.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('PQW2VMCQ', 'Perfumes', 'Perfume3', 6.0, 3924.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('X9DVNU80', 'Tshirts', 'Tshirt1', 5.0, 2890.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('GVS8Q349', 'Tshirts', 'Tshirt4', 10.0, 11670.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('Z9SVN7N1', 'Tshirts', 'Tshirt5', 1.0, 753.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('LUNJ48VF', 'Water bottles', 'Bottle5', 6.0, 3402.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('8ZOV7LN2', 'Tshirts', 'Tshirt5', 6.0, 4902.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('XPNNGH8R', 'Jeans', 'Jeans6', 9.0, 5355.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('ST0SX5WV', 'Jeans', 'Jeans2', 5.0, 3015.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('ZBNZ8V12', 'Jeans', 'Jeans2', 10.0, 6690.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('N89QKNS8', 'Jeans', 'Jeans5', 8.0, 5584.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('X5TD44K1', 'Jeans', 'Jeans5', 5.0, 2765.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('D6357OON', 'Shoes', 'Shoes4', 3.0, 2841.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('74X2EK3Z', 'Smart Phone', 'Phone1', 1.0, 826.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('6AHF7VP1', 'Jeans', 'Jeans6', 10.0, 5050.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('XWC4RTWU', 'Jeans', 'Jeans3', 4.0, 3716.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('MUGYSM8T', 'Water bottles', 'Bottle2', 1.0, 1129.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('BNN0MCIX', 'Perfumes', 'Perfume5', NULL, NULL);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('BT3G2QZW', 'Tshirts', 'Tshirt5', 6.0, 3816.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('KBHB7S9T', 'Jeans', 'Jeans1', 8.0, 4296.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('M25LEN60', 'Shoes', 'Shoes1', 4.0, 3168.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('N2JCPP9G', 'Smart Phone', 'Phone3', 8.0, 8072.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('KQZFPQ06', 'Shoes', 'Shoes3', 6.0, 7056.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('YOS0FB4Y', 'Perfumes', 'Perfume4', 1.0, 576.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('NNUVY8N1', 'Smart Phone', 'Phone1', 4.0, 4640.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('XIE0RNUJ', 'Perfumes', 'Perfume2', 7.0, 5747.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('Y9HECGZ9', 'Shoes', 'Shoes6', 10.0, 7920.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('T64Z7W2S', 'Water bottles', 'Bottle3', 2.0, 2126.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('ATN2TWDL', 'Tshirts', 'Tshirt2', 4.0, 4020.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('3C9XQYM5', 'Water bottles', 'Bottle6', 7.0, 6433.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('S53SKF7I', 'Perfumes', 'Perfume6', 3.0, 2829.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('WTEKTSG7', 'Perfumes', 'Perfume3', 5.0, 3505.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('4U3BBXUX', 'Jeans', 'Jeans2', 10.0, 8450.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('6TXKI3OQ', 'Perfumes', 'Perfume4', 1.0, 1009.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('QMF5L9MO', 'Water bottles', 'Bottle1', 7.0, 6965.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('QJIDKNWI', 'Shoes', 'Shoes5', 6.0, 4482.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('1RSRLA8S', 'Jeans', 'Jeans3', 6.0, 4164.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('KV4YKADE', 'Jeans', 'Jeans2', 1.0, 551.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('BBUNKNQT', 'Shoes', 'Shoes6', 7.0, 6118.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('O2M71HSS', 'Perfumes', 'Perfume6', 3.0, 1797.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('SF6F7LOW', 'Tshirts', 'Tshirt1', 6.0, 5910.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('RURALDOL', 'Shoes', 'Shoes5', 9.0, 9405.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('JX8UIBRS', 'Water bottles', 'Bottle6', 10.0, 9850.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('3IUZGPPO', 'Water bottles', 'Bottle5', 7.0, 4557.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('50CEHLXS', 'Jeans', 'Jeans4', 10.0, 9820.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('TY5Y2JR8', 'Shoes', 'Shoes2', 9.0, 7650.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('ZYRRU7ZK', 'Shoes', 'Shoes5', 5.0, 3975.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('82KKZMPJ', 'Perfumes', 'Perfume6', 7.0, 5971.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('7ZEWVIYT', 'Smart Phone', 'Phone2', 9.0, 6993.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('ZD1AT7O7', 'Water bottles', 'Bottle2', 7.0, 5866.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('KC1XI04B', 'Smart Phone', 'Phone4', 5.0, 4140.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('9OR7875A', 'Jeans', 'Jeans4', 3.0, 1611.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('QXS6ESJ3', 'Perfumes', 'Perfume5', 6.0, 4746.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('AMKYGVWO', 'Shoes', 'Shoes2', 5.0, 3450.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('D9R7ANQJ', 'Smart Phone', 'Phone5', 7.0, 8295.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('JMIYQFY7', 'Shoes', 'Shoes3', 10.0, 5110.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('WHEF0VOT', 'Water bottles', 'Bottle3', 5.0, 4380.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('YV2STN7E', 'Smart Phone', 'Phone5', 4.0, 3012.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('F4PYZR6Q', 'Perfumes', 'Perfume5', 9.0, 5877.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('UUYLAJAH', 'Tshirts', 'Tshirt4', 7.0, 6769.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('97C7BO11', 'Tshirts', 'Tshirt1', 2.0, 2108.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('Q7NC85E4', 'Water bottles', 'Bottle6', 6.0, 5346.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('E9419QZP', 'Tshirts', 'Tshirt2', 7.0, 7287.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('J70E3P15', 'Smart Phone', 'Phone2', 6.0, 3948.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('BVZB0OIH', 'Tshirts', 'Tshirt2', 2.0, 2216.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('30LVYLKF', 'Tshirts', 'Tshirt2', 5.0, 3695.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('C856WPR9', 'Water bottles', 'Bottle5', 5.0, 3905.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('ZOKGTII4', 'Water bottles', 'Bottle6', 9.0, 7434.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('8UEIHX74', 'Jeans', 'Jeans4', 9.0, 8298.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('JYV5G10U', 'Tshirts', 'Tshirt5', 4.0, 2208.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('8A78E9RI', 'Smart Phone', 'Phone2', 6.0, 4860.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('LKQXLM5Q', 'Perfumes', 'Perfume6', 4.0, 4260.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('NOUHFJ7U', 'Water bottles', 'Bottle4', 6.0, 4248.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('N4RXYJ38', 'Smart Phone', 'Phone3', 6.0, 4410.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('GZR7TXCB', 'Water bottles', 'Bottle6', 3.0, 2580.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('O4IZASNW', 'Tshirts', 'Tshirt6', NULL, NULL);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('ATATJ9A3', 'Water bottles', 'Bottle5', 8.0, 4128.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('7SIWJM2C', 'Water bottles', 'Bottle4', 3.0, 1827.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('Y4X41DNT', 'Smart Phone', 'Phone4', 4.0, 3228.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('C4XL9967', 'Tshirts', 'Tshirt6', NULL, NULL);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('J7YKTXG4', 'Jeans', 'Jeans2', 10.0, 9860.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('KUU4YTN0', 'Tshirts', 'Tshirt2', 7.0, 4046.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('DICVWV8L', 'Water bottles', 'Bottle6', 6.0, 3324.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('ITNGVN1K', 'Water bottles', 'Bottle3', 8.0, 8016.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('N2FOMD7Q', 'Jeans', 'Jeans6', 5.0, 3285.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('QTOAMDVL', 'Shoes', 'Shoes1', 3.0, 2823.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('0U9ISYGJ', 'Smart Phone', 'Phone1', 7.0, 4102.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('JK2N7ZRW', 'Shoes', 'Shoes4', 3.0, 2835.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('LW2LM349', 'Smart Phone', 'Phone1', 1.0, 905.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('L88KZRUI', 'Jeans', 'Jeans3', 4.0, 3960.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('EUVTYT8Q', 'Smart Phone', 'Phone3', 7.0, 6111.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('32ORWIXZ', 'Water bottles', 'Bottle2', 5.0, 2850.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('UT75PB8Z', 'Smart Phone', 'Phone1', 10.0, 9900.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('1XMXB9YO', 'Perfumes', 'Perfume5', 2.0, 1222.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('H0UYHNQY', 'Shoes', 'Shoes4', 2.0, 1528.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('DO8E7FLQ', 'Water bottles', 'Bottle5', 1.0, 994.0);
INSERT INTO IndiaSales (SaleId, Category, Product, Qty, Sale) VALUES ('PZLK3E4X', 'Jeans', 'Jeans5', 8.0, 4792.0);
