INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('R7WB42P3', 'Jeans', 'Jeans3', 9.0, 70.2);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('RVZ90472', 'Smart Phone', 'Phone2', 10.0, 128.8);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('6BGUAXNM', 'Perfumes', 'Perfume4', 6.0, 47.16);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('EDS1VRTT', 'Water bottles', 'Bottle1', 8.0, 52.48);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('LL3K4BK8', 'Shoes', 'Shoes1', 1.0, 12.89);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('K499NR0O', 'Jeans', 'Jeans6', 7.0, 51.31);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('7V4NDJM5', 'Tshirts', 'Tshirt3', 2.0, 14.3);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('BL116CZ7', 'Jeans', 'Jeans5', 2.0, 16.48);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('K61B7PXJ', 'Water bottles', 'Bottle5', 9.0, 117.99);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('DRQNTJVU', 'Tshirts', 'Tshirt2', 10.0, 56.3);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('7ZD3Q0E0', 'Jeans', 'Jeans1', 3.0, 39.03);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('Y5U04RIP', 'Water bottles', 'Bottle5', 7.0, 39.55);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('MOV6KI4E', 'Perfumes', 'Perfume6', 9.0, 80.37);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('9OGJEGXE', 'Smart Phone', 'Phone3', 8.0, 44.8);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('900YEH8U', 'Water bottles', 'Bottle2', 1.0, 8.23);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('DHF025LO', 'Water bottles', 'Bottle2', 1.0, 10.32);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('HWHM54XR', 'Water bottles', 'Bottle5', 8.0, 105.44);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('PF240SHD', 'Shoes', 'Shoes4', NULL, NULL);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('1R1CQKIH', 'Shoes', 'Shoes2', 3.0, 31.38);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('RPE2XN9T', 'Shoes', 'Shoes4', 5.0, 37.1);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('JD5SLOC8', 'Water bottles', 'Bottle2', 6.0, 69.36);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('1YUW2TGR', 'Tshirts', 'Tshirt2', 5.0, 41.9);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('11PMRG0Z', 'Perfumes', 'Perfume1', 1.0, 9.33);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('HO4VUDQH', 'Smart Phone', 'Phone3', 5.0, 61.5);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('M1TRPUYD', 'Jeans', 'Jeans3', NULL, NULL);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('QT0D9TZH', 'Jeans', 'Jeans2', 1.0, 7.93);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('AVEKVQHM', 'Jeans', 'Jeans2', 1.0, 8.52);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('TW1BYTXZ', 'Jeans', 'Jeans5', 5.0, 62.15);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('5DSIUAZ7', 'Tshirts', 'Tshirt4', 4.0, 41.2);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('9UYG3IBG', 'Smart Phone', 'Phone5', 1.0, 6.7);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('XIEE6HW5', 'Jeans', 'Jeans2', 8.0, 50.24);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('RANTY6D1', 'Shoes', 'Shoes6', 2.0, 14.8);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('I3JSTY87', 'Jeans', 'Jeans1', 2.0, 21.12);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('TU8PV2KJ', 'Perfumes', 'Perfume3', 3.0, 37.17);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('ONT75EZ6', 'Jeans', 'Jeans6', 1.0, 7.83);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('R6U0ESTI', 'Jeans', 'Jeans6', 2.0, 24.0);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('TCTDSDJT', 'Jeans', 'Jeans2', 9.0, 112.77);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('2HWSWCZT', 'Jeans', 'Jeans1', 4.0, 28.76);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('B121Y50D', 'Water bottles', 'Bottle3', 5.0, 47.25);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('CG8D2TN2', 'Jeans', 'Jeans6', 10.0, 65.2);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('9LY2SKKF', 'Water bottles', 'Bottle5', NULL, NULL);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('RR6CG1S2', 'Perfumes', 'Perfume2', 10.0, 117.6);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('QBBX5NWD', 'Shoes', 'Shoes4', 9.0, 95.04);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('NEO2S9NB', 'Water bottles', 'Bottle5', 3.0, 30.66);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('TBQOIVWQ', 'Shoes', 'Shoes2', 7.0, 42.42);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('EC275JT6', 'Shoes', 'Shoes1', 9.0, 69.3);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('08XTR5IG', 'Perfumes', 'Perfume6', NULL, NULL);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('JFCZWKGU', 'Water bottles', 'Bottle2', 2.0, 20.32);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('FIPZN0TH', 'Water bottles', 'Bottle6', 7.0, 62.93);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('K9OM115B', 'Shoes', 'Shoes3', 1.0, 10.05);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('TGG50YQL', 'Smart Phone', 'Phone2', 6.0, 56.88);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('6AIDIZS3', 'Shoes', 'Shoes3', 9.0, 102.33);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('VZYMKX9K', 'Shoes', 'Shoes3', 3.0, 32.73);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('3JLZOHFD', 'Jeans', 'Jeans2', 6.0, 46.8);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('Z2TVHVWH', 'Tshirts', 'Tshirt6', 9.0, 98.28);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('BOBCD11R', 'Jeans', 'Jeans2', 6.0, 49.02);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('2ZSA6HA3', 'Shoes', 'Shoes4', 9.0, 92.16);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('T4SAYMWR', 'Perfumes', 'Perfume1', 7.0, 48.02);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('8675YOVM', 'Water bottles', 'Bottle3', 10.0, 69.5);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('5XUDKITM', 'Tshirts', 'Tshirt1', 2.0, 14.0);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('G07VSCQM', 'Tshirts', 'Tshirt5', 7.0, 54.67);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('ET7BNA2I', 'Smart Phone', 'Phone1', 1.0, 8.95);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('YEE2ABG9', 'Smart Phone', 'Phone4', 1.0, 11.53);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('D5AFQL0D', 'Perfumes', 'Perfume2', 7.0, 87.78);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('BPTPDWR1', 'Jeans', 'Jeans2', 6.0, 57.96);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('K8EKT292', 'Water bottles', 'Bottle2', 9.0, 77.49);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('EBIN0BYQ', 'Shoes', 'Shoes3', 9.0, 104.76);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('NUZ2KGA9', 'Water bottles', 'Bottle1', 1.0, 11.39);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('ZWW1UN2K', 'Shoes', 'Shoes5', 7.0, 87.01);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('Y9Q6KTNN', 'Perfumes', 'Perfume6', 10.0, 133.3);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('K15U2486', 'Perfumes', 'Perfume2', 10.0, 67.6);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('21PU8BWA', 'Tshirts', 'Tshirt2', 4.0, 35.8);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('19BP0L70', 'Perfumes', 'Perfume4', 2.0, 21.64);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('X6SXUA3K', 'Perfumes', 'Perfume5', 10.0, 97.3);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('6UPB22O1', 'Tshirts', 'Tshirt3', 2.0, 14.42);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('2NNOC3AR', 'Perfumes', 'Perfume6', 5.0, 33.25);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('3LM7E41O', 'Smart Phone', 'Phone1', 3.0, 23.28);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('J643F1AY', 'Jeans', 'Jeans2', 5.0, 57.05);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('9E9NHCGW', 'Perfumes', 'Perfume4', 7.0, 44.17);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('CXCWC0BO', 'Tshirts', 'Tshirt1', 7.0, 81.41);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('XWBNWJ6P', 'Jeans', 'Jeans6', 10.0, 106.5);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('501OEEA2', 'Perfumes', 'Perfume3', 1.0, 10.72);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('79U7C1A7', 'Water bottles', 'Bottle4', 8.0, 79.84);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('HI78LZGM', 'Water bottles', 'Bottle5', 4.0, 31.44);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('A46FDVAE', 'Smart Phone', 'Phone1', 2.0, 21.8);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('QT9NGQ6T', 'Smart Phone', 'Phone2', 6.0, 42.6);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('LFOS9DJ9', 'Shoes', 'Shoes3', 3.0, 36.63);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('OT760RS6', 'Jeans', 'Jeans4', 5.0, 33.75);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('6V3DGS9G', 'Tshirts', 'Tshirt1', 2.0, 22.42);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('P15I3IES', 'Perfumes', 'Perfume3', 8.0, 100.24);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('MUQ0RZTW', 'Perfumes', 'Perfume6', 7.0, 41.37);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('RC4R6S34', 'Smart Phone', 'Phone6', 2.0, 21.56);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('FXGIMYDO', 'Tshirts', 'Tshirt3', 7.0, 82.39);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('TQDJU0S1', 'Water bottles', 'Bottle3', NULL, NULL);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('U818UTYI', 'Jeans', 'Jeans1', 3.0, 27.99);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('8E7428YI', 'Perfumes', 'Perfume5', 9.0, 51.93);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('SKE5M0SW', 'Perfumes', 'Perfume4', 10.0, 84.5);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('TQ36ZPMG', 'Water bottles', 'Bottle1', 8.0, 102.08);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('T8G7QNCW', 'Perfumes', 'Perfume4', 8.0, 62.64);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('VRT4UPR4', 'Water bottles', 'Bottle6', 8.0, 90.0);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('9BXLSOGW', 'Jeans', 'Jeans3', 4.0, 44.96);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('X51O0LQB', 'Jeans', 'Jeans3', 5.0, 29.65);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('2MNJ7OVH', 'Water bottles', 'Bottle1', 9.0, 68.4);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('8Y0423H7', 'Shoes', 'Shoes5', 4.0, 51.4);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('FCYLTM9R', 'Perfumes', 'Perfume5', 6.0, 61.32);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('OV5IT2NI', 'Shoes', 'Shoes4', 10.0, 75.5);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('N8RJN4LV', 'Perfumes', 'Perfume1', 7.0, 68.74);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('ALW563C3', 'Smart Phone', 'Phone6', 5.0, 40.75);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('SZUJB4HL', 'Smart Phone', 'Phone5', 1.0, 7.86);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('HHGWHP08', 'Shoes', 'Shoes3', 6.0, 55.98);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('B8J4ZXD8', 'Tshirts', 'Tshirt2', 8.0, 73.68);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('NT9ZSUV4', 'Tshirts', 'Tshirt1', 3.0, 32.43);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('4S4MFEL3', 'Smart Phone', 'Phone1', 3.0, 24.81);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('S2QPKGRM', 'Smart Phone', 'Phone4', 6.0, 73.56);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('W0PN524K', 'Shoes', 'Shoes6', 5.0, 58.9);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('83PLE45B', 'Perfumes', 'Perfume2', 10.0, 69.4);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('5CIX39EL', 'Shoes', 'Shoes3', 10.0, 129.9);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('RSWP0YKK', 'Shoes', 'Shoes1', 6.0, 56.88);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('WZF8Y7P6', 'Perfumes', 'Perfume5', 7.0, 86.1);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('0E49Z7K8', 'Smart Phone', 'Phone6', 7.0, 51.1);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('3DE4EV5X', 'Tshirts', 'Tshirt5', 3.0, 35.43);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('05SORHTM', 'Water bottles', 'Bottle3', 1.0, 9.9);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('ZXGGMQJ9', 'Perfumes', 'Perfume2', 7.0, 80.71);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('FUBFD340', 'Perfumes', 'Perfume6', 3.0, 29.79);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('B5Z8XGQH', 'Smart Phone', 'Phone6', 2.0, 20.14);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('UG4BGF86', 'Smart Phone', 'Phone6', 10.0, 130.9);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('02XVXITI', 'Jeans', 'Jeans6', 3.0, 20.22);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('4TL7JE0Q', 'Jeans', 'Jeans3', 4.0, 48.8);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('IAL5U8RZ', 'Water bottles', 'Bottle4', 7.0, 62.3);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('PGGCBI6Q', 'Tshirts', 'Tshirt2', 10.0, 122.5);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('Z3E88SEB', 'Perfumes', 'Perfume4', 4.0, 44.8);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('00BGBB1R', 'Water bottles', 'Bottle1', 6.0, 60.78);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('PYYZ5YMI', 'Water bottles', 'Bottle4', 9.0, 108.9);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('A9INCU2L', 'Perfumes', 'Perfume4', 1.0, 7.89);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('5U7D2XG7', 'Smart Phone', 'Phone1', 3.0, 23.97);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('KRX0GWHA', 'Perfumes', 'Perfume6', 1.0, 6.64);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('D8FBFFHE', 'Smart Phone', 'Phone4', 10.0, 113.0);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('1FE1YEND', 'Water bottles', 'Bottle6', 7.0, 76.44);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('EM0TPI70', 'Jeans', 'Jeans1', 1.0, 10.7);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('NHAGXXKS', 'Jeans', 'Jeans1', 4.0, 42.08);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('AUOS74UL', 'Jeans', 'Jeans3', 2.0, 17.68);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('A3G49MN2', 'Jeans', 'Jeans2', 7.0, 49.35);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('UM2V31IQ', 'Water bottles', 'Bottle6', 4.0, 52.84);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('LNL7HA75', 'Jeans', 'Jeans3', 6.0, 71.22);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('PNFIRCVC', 'Jeans', 'Jeans1', 8.0, 49.6);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('5AIEKX6M', 'Water bottles', 'Bottle6', 7.0, 73.22);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('Z5BCAN68', 'Shoes', 'Shoes2', 1.0, 8.13);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('WNV2MK48', 'Perfumes', 'Perfume6', 7.0, 63.77);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('QABCE2EH', 'Shoes', 'Shoes4', 3.0, 25.38);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('O1DFSTS3', 'Water bottles', 'Bottle4', 2.0, 21.46);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('BZ9ZQHBQ', 'Water bottles', 'Bottle3', 3.0, 37.08);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('CB5NTJK2', 'Jeans', 'Jeans1', 4.0, 37.56);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('UGTTMPPJ', 'Jeans', 'Jeans1', 1.0, 5.78);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('HY5HO37P', 'Tshirts', 'Tshirt2', 1.0, 9.4);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('CVS3ZRB9', 'Shoes', 'Shoes4', 7.0, 51.03);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('WACEQRQ6', 'Smart Phone', 'Phone4', 5.0, 46.85);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('I1T3UZZZ', 'Tshirts', 'Tshirt1', 5.0, 61.45);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('2BVS3K33', 'Perfumes', 'Perfume1', 2.0, 18.42);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('ICQPEOV0', 'Smart Phone', 'Phone5', 8.0, 103.2);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('HKBRJIGL', 'Tshirts', 'Tshirt4', 2.0, 14.58);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('VKUEV3C3', 'Jeans', 'Jeans2', 9.0, 119.25);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('HBQ64DO4', 'Shoes', 'Shoes2', 3.0, 17.64);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('46T9DNZW', 'Water bottles', 'Bottle6', 5.0, 33.35);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('66DQA4SV', 'Perfumes', 'Perfume5', 10.0, 107.2);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('76KE1Q5M', 'Shoes', 'Shoes6', 2.0, 23.68);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('9N7TCATP', 'Perfumes', 'Perfume6', 10.0, 106.2);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('NDVDXDF6', 'Shoes', 'Shoes4', 3.0, 23.25);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('YUSQ1U97', 'Water bottles', 'Bottle5', 3.0, 37.35);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('VIE6DUEP', 'Smart Phone', 'Phone6', 5.0, 30.4);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('K6YULND7', 'Smart Phone', 'Phone5', 3.0, 33.51);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('KBVPX4NT', 'Perfumes', 'Perfume6', 7.0, 53.69);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('JSFPFMNF', 'Water bottles', 'Bottle3', 7.0, 41.16);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('TESU2HTT', 'Shoes', 'Shoes5', 7.0, 61.11);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('9OF9SVCA', 'Perfumes', 'Perfume2', 7.0, 50.05);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('V10M1V39', 'Tshirts', 'Tshirt1', 4.0, 27.52);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('ROAGI7LS', 'Jeans', 'Jeans6', 4.0, 32.12);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('M81RJWPX', 'Smart Phone', 'Phone3', 1.0, 7.48);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('O4Q067CS', 'Jeans', 'Jeans6', 1.0, 12.07);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('WT805QTD', 'Water bottles', 'Bottle3', 10.0, 118.4);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('24W7W8TW', 'Tshirts', 'Tshirt4', 9.0, 61.11);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('OWP7NL6D', 'Perfumes', 'Perfume5', 4.0, 48.96);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('BEEVG429', 'Shoes', 'Shoes5', 6.0, 78.84);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('ERP0IV1T', 'Jeans', 'Jeans6', 1.0, 9.6);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('9XDULVNA', 'Smart Phone', 'Phone2', 4.0, 41.16);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('3K8JB79Y', 'Tshirts', 'Tshirt5', 10.0, 90.3);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('POLPF37L', 'Shoes', 'Shoes6', 10.0, 105.6);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('6U2LLH22', 'Shoes', 'Shoes4', 6.0, 70.44);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('2524GPZB', 'Tshirts', 'Tshirt4', 6.0, 51.24);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('IBZYFGGK', 'Smart Phone', 'Phone6', 10.0, 95.6);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('RO1WODGZ', 'Smart Phone', 'Phone4', 8.0, 104.8);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('TSNC19AR', 'Tshirts', 'Tshirt1', 9.0, 76.14);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('E5GV7P2A', 'Perfumes', 'Perfume4', 8.0, 95.84);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('4WPFDFHJ', 'Shoes', 'Shoes4', 7.0, 60.2);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('Z05TQM3G', 'Water bottles', 'Bottle4', 7.0, 66.85);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('YZILJ29J', 'Shoes', 'Shoes5', 3.0, 21.0);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('XKQ054CF', 'Tshirts', 'Tshirt6', 5.0, 45.4);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('1W09YW3D', 'Jeans', 'Jeans2', 8.0, 70.8);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('KX0RB5TN', 'Smart Phone', 'Phone4', 4.0, 52.76);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('XC4VNIBL', 'Jeans', 'Jeans1', 6.0, 34.32);
INSERT INTO GermanySales (SaleId, Category, Product, Qty, Sale) VALUES ('99LT3J6L', 'Water bottles', 'Bottle2', NULL, NULL);
